---
title: "Estadística 101"
---

<br/>
Este curso se basa en <a href="https://www.goodreads.com/book/show/578667.Statistics_Without_Tears" target="_blank">Statistics without tears</a> de Derek Rowntree y <a href="https://www.discoveringstatistics.com/books/discovering-statistics-using-r/" target="_blank">Discovering statistics using R</a>  de Andy Field, Jeremy Miles y Zoë Field. Dicho eso, cualquier error que puedas encontrar es mi responsabilidad.<br/>
Este curso también utiliza material del libro "Discovering statistics using R". Este material no me pertenece y es accesible <a href="https://studysites.uk.sagepub.com/dsur/study/articles.htm" target="_blank">aquí.</a>

Este curso asume que no sabes nada de estadística. Sin embargo, si asume que sabes lo básico de aritmética y fracciones. La mejor manera de aprender es que respondas las preguntas clave de cada capítulo. Y que realizes los ejercicios con la ayuda de Jamovi. La base de datos que vamos a utilizar se encuentra <a href="https://github.com/joseluisulloafulgeri/estadistica101_database" target="_blank">aquí.</a> ¡Que disfrutes el curso!<br/><br/>

## <a href="https://www.youtube.com/playlist?list=PLzyW6TZJNgGaCt1fDe0vl-pBt_Y4A0uaU" target="_blank">Capítulo 1a: ¿Para que nos sirve la estadística?</a>

Contenido: 4 videos (27 minutos en total)

Preguntas clave:

- ¿Qué es la estadística descriptiva? ¿Qué es la estadística inferencial?
- ¿Qué es una población y una muestra? ¿Qué son los parámetros y los estadísticos?
- ¿Por qué necesitamos obtener una muestra para nuestros experimentos?
- ¿Por qué necesitamos las probabilidades para análisis estadísticos?

- ¿Que tipos de variables nos sirven para describir una muestra?
- ¿Que significa definir variables y operacionalizar?
- ¿Que es una variable independiente? ¿Que es una variable dependiente?
- ¿Cómo se construye una hipótesis?

- En un diseño experimental ¿qué es un factor?
- En un diseño experimental ¿qué es un nivel?
- ¿Cuál es la diferencia entre un diseño intra-sujetos y un diseño entre-sujetos?
- ¿Qué es un diseño experimental mixto?
- ¿Qué tipo de prueba se utiliza para comparar dos grupos experimentales?
- ¿Qué tipo de prueba se utiliza para comparar mas de dos grupos experimentales?
<br/><br/>

## <a href="https://www.youtube.com/playlist?list=PLzyW6TZJNgGZdIZuvGySMRfKq2r1UKnCg" target="_blank">Capítulo 1b: ¿Que es lo más esencial que debería saber?</a>

Contenido: 6 videos (41 minutos en total)

Preguntas clave:

- ¿Qué aspectos son importantes a la hora de diseñar un experimento?
- ¿Qué es la validez de una medición?
- ¿Qué es la replicabilidad de una medición?
- ¿Qué es un factor confundente?

- ¿Qué hace un prueba estadística (en términos de los cambios que experimenta una variable)?
- ¿Qué es la variación sistemática? ¿Qué es la variación no sistemática?

- ¿Cuál es la diferencia entre un diseño intra-sujetos y un diseño entre-sujetos?
- ¿Cuál es la relación entre un diseño experimental y su análisis estadístico asociado?

- ¿Quién fué Roland Fisher?
- ¿Dé dónde viene el 5% (o p = 0.05) que usamos en estadística?

- ¿Para que se usa la randomización?
- ¿Qué son los efectos de práctica y de aburrimiento en un diseño intra-sujetos?
- ¿Cómo podemos confeccionar un buen diseño entre-sujetos?

<a href="https://www.youtube.com/watch?v=K0djrU94yvg&ab_channel=Jos%C3%A9LuisBlues" target="_blank"><span style="color:blue">Estadística en la práctica 1: Instalando Jamovi (2.5 minutos)</span></a>
<br/><br/>

## <a href="https://www.youtube.com/playlist?list=PLzyW6TZJNgGYNH1thjd8KkRyr-JVPzvR3" target="_blank">Capítulo 2: ¿Por qué importa tanto tanto la curva normal?</a>

Contenido: 8 videos (1 hora 32 minutos en total)

- ¿Por qué es importante graficar los datos?
- ¿Cómo se calcula la desviación estándar?
- ¿Qué es la suma de cuadrados (o suma de los errores al cuadrado)?

- ¿Cómo se puede visualizar la "forma" de los datos?
- ¿Qué características tiene la curva normal?
- ¿Cómo estimamos cuantas observaciones caen entre dos valores para una set de datos?
- ¿Qué porcentaje de los datos esta entre -1 SD y 1 SD?

- ¿Qué significa generalizar nuestros hallazgos?
- ¿Qué es la variación de la muestra (o sampling variation)?
- ¿Qué es el error estándar y como se calcula?
- ¿Qué son los intervalos de confianza?
- ¿Qué significa que cálculemos un intervalo de confianza al 68% para un valor?
- ¿Qué significa que cálculemos un intervalo de confianza al 95% para un valor?

<a href="https://www.youtube.com/watch?v=1DaF6lau7hA&ab_channel=Jos%C3%A9LuisBlues" target="_blank"><span style="color:blue">Estadística en la práctica 2: Explorando mis datos (17 minutos)</span></a>
<br/><br/>

## <a href="https://www.youtube.com/playlist?list=PLzyW6TZJNgGbZKFJCnsK8Sxd840FatDm-" target="_blank">Capítulo 3: ¿Que es un t-test?</a>

Contenido: 4 videos (45 minutos en total)

- ¿Cómo comparamos dos grupos de datos?

<a href="https://www.youtube.com/watch?v=-XgeZ-cAtEc&ab_channel=Jos%C3%A9LuisBlues" target="_blank"><span style="color:blue">Estadística en la práctica 3: T-test entre-sujetos (23 minutos)</span></a>

## <a href="https://www.youtube.com/playlist?list=PLzyW6TZJNgGaAEQlidg92YdaCvYBCWoSj" target="_blank">Capítulo 4: ¿Que es un modelo estadístico?</a>

Contenido: 3 videos (39 minutos en total)

- ¿Qué es un modelo?
- ¿Qué es un modelo estadístico?

<br/>

## <a href="https://www.youtube.com/playlist?list=PLzyW6TZJNgGaJHRDX7kGcfA659l8FMRAO" target="_blank">Capítulo 5: ¿Que es un ANOVA?</a>

Contenido: 4 videos (53 minutos en total)

- ¿Cómo comparamos varias condiciones experimentales?

<br/>

## <a href="https://www.youtube.com/playlist?list=PLzyW6TZJNgGaIAxM2bxJVkNDbKs5KnaId" target="_blank">Capítulo 6: ¿Y que hago después que calculo un ANOVA?</a>

Contenido: 3 videos (35 minutos en total)

- ¿Que hago después de una prueba omnibus?
